name: TradingStocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - statsmodels=0.14.2
  - yfinance=0.2.40
  - ta-lib=0.4.32
  - pandas-datareader=0.10.0
  - scikit-learn=1.4.2
  - pyportfolioopt=1.5.5
